### ISSUE TITLE
[Suggestion] Enemy HUD bar

### ISSUE THREAD

**Issue by NotxFound** [shudnal/MyLittleUI#10]
I don't know if you are gonna work on that, but it would be great to see a updated/new enemy HP bar, which would display their HP in numbers + the bar instead of the vanilla bar. 

For a better comparison you can take a look at the BetterUI mod where it is included.

**Comment by shudnal** [comment]
There is [Enhuddlement](https://thunderstore.io/c/valheim/p/ComfyMods/Enhuddlement/). It is made well, maintained and updated. I don't think there is any need of duplicating the same feature. And at last I don't use custom hud and I can't make this a good feature without my own vision how it should work.
