### ISSUE TITLE
my friend can't connect

### ISSUE THREAD

**Issue by nlineprime** [shudnal/MyLittleUI#11]
as soon as I add this mod my friend can't connect
which mod is the problem?
https://sun9-25.userapi.com/impg/fQDZsd4wfPK_OOOvQ-46P73_nB02c-yGTVkYoQ/-ufQMSls2fI.jpg?size=1264x748&quality=96&sign=f6045952e7182bb176dd7ff83a0fa3e7&type=album
[LogOutput.log](https://github.com/user-attachments/files/17894545/LogOutput.log)
its my log file

**Comment by shudnal** [comment]
[MyLittleUI.zip](https://github.com/user-attachments/files/17894982/MyLittleUI.zip)
Could you check if this version works?

**Comment by nlineprime** [comment]
the error is not observed, as soon as my friend returns, we will try and I will unsubscribe whether it works or not

**Comment by shudnal** [comment]
Fix is live in 1.1.21 version.
