### ISSUE TITLE
Game crashes if a chest is open with AzuCraftyBoxes & MyLittleUi installed

### ISSUE THREAD

**Issue by mdsmendes94** [shudnal/MyLittleUI#4]
Opening a chest with mods enabled crashes the game
Entering the Workbench with a chest nearby also crashes the game

How to reproduce:

1. Have both AzuCraftBoxes & MyLittleUi installed
2. Open a chest
3. Game crashes

[LogOutput.log](https://github.com/user-attachments/files/17580054/LogOutput.log)

**Comment by shudnal** [comment]
You can temporary disable Multicraft option.

**Comment by shudnal** [comment]
Thanks. Fixed in 1.1.9.
