### ISSUE TITLE
Suggestion: Expose tame's pregnancy %age

### ISSUE THREAD

**Issue by Karmacopper** [shudnal/MyLittleUI#6]
Just that :D

**Comment by shudnal** [comment]
Well whole **Hover - Character** is already dedicated to that.

**Comment by Karmacopper** [comment]
Sorry, I think I miswrote this. I mean the love point count.

**Comment by shudnal** [comment]
And now I have no idea what you mean.

**Comment by Karmacopper** [comment]
Sorry, I was referencing the Valheim Wiki. [Breeding](https://valheim.fandom.com/wiki/Taming?so=search)

**Comment by shudnal** [comment]
Version 1.1.19 is ready https://thunderstore.io/c/valheim/p/shudnal/MyLittleUI/versions/
