### ISSUE TITLE
Issues with last update on server.

### ISSUE THREAD

**Issue by Karmacopper** [shudnal/MyLittleUI#7]
After the last update when you so kindly added love points for tames, I notice some unrelated issues. It is not installed on the server and was the only client-side update at the time.

Smelters and charcoal kilns stopped ticking (no output), although they still animate. I destroyed and rebuilt them multiple times, in different locations.

Tames were regaining fed buff without being fed.

After rolling back and once the smelters and charcoal kilns were rebuilt, everything returned to normal. Client-side mod list available on request.

**Comment by shudnal** [comment]
Well nothing else was changed except `Character.GetHoverText` method
https://github.com/shudnal/MyLittleUI/commit/2e4522e88f64c8a5f6cc4c0dadfb61515173fc71

More so mod doesn't touch any server logic. Its server sided component is only config synchronisation. Maybe you have some errors in log file idk.

**Comment by shudnal** [comment]
1.1.20 should work.

**Comment by Karmacopper** [comment]
Can confirm, the ticks are ticking again.
