### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by gabsc9** [shudnal/MyLittleUI#9]
Hello

If I may suggest something, it is an option to change the position of the filter at the crafting menu, it currently blocks the last line in the crafting list.

Thanks for the great mods.

**Comment by gabsc9** [comment]
Good call, I think it was 'CraftingFilter' by cjayride causing that issue.

**Comment by shudnal** [comment]
I had this issue too when craft filter feature was first released but it was reported and I've fixed that. 
If you use another craft filter mod you better disable this feature in MLUI to prevent possible issues.
